server:
  port: 10086
spring:
  application:
    name: chat-registry
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:10086/eureka
    register-with-eureka: false
    fetch-registry: false
    instance:
      prefer-ip-address: true
      ip-address: 192.168.1.112