server:
  port: 8091

spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql@2018BaiYan.Com
  redis:
    database: 0
    port: 6379
    host: localhost
    password: lng_baiyan
    authtime: 6000 #用于登录的时候查询用户的信息保存到redis的存活时间
    authprefix: anthUserMsg# #用于用户登录的时候,用户信息保存redis的key前缀
# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: localhost
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间